// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnjIDIpu7-mcn-3lbcgI0MYA6ijG7rA9s',
    appId: '1:1064502753004:android:735e8e5f4eb62368db57c9',
    messagingSenderId: '1064502753004',
    projectId: 'chat-app2-e7dec',
    storageBucket: 'chat-app2-e7dec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBedJy5SSvHziP60dbOqe4dJ2QFAn72Kg0',
    appId: '1:1064502753004:ios:cb226e9cc70e7de5db57c9',
    messagingSenderId: '1064502753004',
    projectId: 'chat-app2-e7dec',
    storageBucket: 'chat-app2-e7dec.appspot.com',
    androidClientId: '1064502753004-lp48bcfmpjfrd7pvg599ocbf0793opij.apps.googleusercontent.com',
    iosClientId: '1064502753004-tqbu4imp22nhhf8b8v753chkrak10svn.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatappdemo',
  );
}
